### ISSUE TITLE
[BUG] Passing custom arg is not possible via PEP517 backends

### ISSUE THREAD

**Issue by mgorny** [Marco-Sulla/python-frozendict#72]
OS version:
Gentoo Linux / amd64

Python3 version (python3 -V -V):
Python 3.11.2 (main, Feb 15 2023, 08:19:40) [GCC 12.2.1 20230121]

Steps to reproduce:

1. `python -m build -w`

Actual result (with the python stack trace if present):

```pytb
$ python -m build -w --config-setting=--global-option=py
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for wheel...
running egg_info
writing frozendict.egg-info/PKG-INFO
writing dependency_links to frozendict.egg-info/dependency_links.txt
writing top-level names to frozendict.egg-info/top_level.txt
reading manifest file 'frozendict.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.txt'
writing manifest file 'frozendict.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
/tmp/build-env-eyas52l5/lib/python3.11/site-packages/setuptools/build_meta.py:307: SetuptoolsDeprecationWarning: 
            The arguments ['py'] were given via `--global-option`.
            Please use `--build-option` instead,
            `--global-option` is reserved to flags like `--verbose` or `--quiet`.
            
  warnings.warn(msg, SetuptoolsDeprecationWarning)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'py'

ERROR Backend subprocess exited when trying to invoke build_wheel
```

Apparently this is because the custom option is appended to the end of `sys.argv` rather than position 1. Also, passing non-option strings there is deprecated.

Ideally, could you make the behavior controlled via `os.environ` rather than `sys.argv`? That would be much cleaner.

**Comment by Marco-Sulla** [comment]
Yes, it's in the [TODO list](https://github.com/Marco-Sulla/python-frozendict/issues/34): 

> Ponder to remove the py wheel and make the C Extension optional

Not very difficult to do:
https://cibuildwheel.readthedocs.io/en/stable/faq/#optional-extensions

**Comment by Marco-Sulla** [comment]
It should be fixed with the new release:
https://github.com/Marco-Sulla/python-frozendict/releases/tag/v2.3.5

Can you confirm it?

**Comment by mgorny** [comment]
It's not fixed. We still can't tell it not to try building the C extension for Python 3.11. Furthermore, now we need to explicitly pass `CIBUILDWHEEL=1` to ensure that it silently doesn't ignore unrelated build failures on other Python versions.

**Comment by Marco-Sulla** [comment]
What's the problem of trying to build the C Extension for Python 3.11?

**Comment by Marco-Sulla** [comment]
The problem here is `pip` and not supported platforms.

If someone wants to install the module for an architecture X and the arch X binary is not present on Pypi, pip downloads and install the pure py wheel if present. It does *not* try to install the sdist package, even if present.

On the contrary, if an sdist package is present and a wheel is *not* present, it tries to compile the sdist. But if so, the C Extension *must* be optional by default, or if the sdist install fails, no module will be installed.

This is much more simple for the end user, and a bit more complicated for devs. But I'm confident that devs are much more expert and it's quite trivial for them to add an env variable. I have to do the same on Conda.

Anyway, I could add change how CIBUILDWHEEL works now. If 1, the Extension will be added as mandatory. If zero, the module will be compiled with *no extension*. If None, the above default behavior acts (Ext enabled but optional).

**Comment by mgorny** [comment]
I think something akin #69 is the best option where the user (or packager) can easily say "I want the C extension if it's supported on my interpreter" and the package takes care of "knowing" which Python versions are supported and which are not.

**Comment by Marco-Sulla** [comment]
#69 is not about this, but it's a good solution for your case, since it checks if a dir with C source files exists. If not, the py wheel is produced.

Since no src dir exists for Python 3.11, the PR will enable for 3.11 the py package by default.

This has also a side benefit to have a pure py package on Conda without trouble.

I'll accept the PR.

**Comment by mgorny** [comment]
Thank you.

**Comment by Marco-Sulla** [comment]
Released in 2.3.6, let me know if it's all OK.

**Comment by mgorny** [comment]
Thanks, it seems to work fine for us!
